_name_: rwkv

config:
  model_type: RWKV # or RWKV-ffnPre
  n_embd: 768 
  time_shift: 1
  n_layer: 8
  ctx_len: 1024
  dim_att: 0
  dim_ffn: 0
  pre_ffn: 0
  head_qk: 0
  tiny_att_dim: 0
  tiny_att_layer: -999
  my_ffn_shift: 1
  my_att_shift: 1
  my_pos_emb: 0